# docker-compose file for running PostgreSQL and pgAdmin
# This file is used to define and run multi-container Docker applications

services:
  # PostgreSQL container
  pg-database:
    # use the official PostgreSQL 13 image
    image: postgres:13

    # set environment variables for the container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi

    # mount a volume from the host machine to persist data
    volumes:
      # mount the ny_taxi_postgres_data directory from the host machine
      # to the /var/lib/postgresql/data directory in the container
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data:rw

    # expose port 5432 from the container to the host machine
    ports:
      - "5432:5432"

  # pgAdmin container
  pg-admin:
    # use the official pgAdmin 4 image
    image: dpage/pgadmin4

    # set environment variables for the container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root

    # expose port 8080 from the container to the host machine
    ports:
      - "8080:80"

    # make sure the pgAdmin container only starts once the PostgreSQL
    # container is up and running
    depends_on:
      - pg-database
